# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # -------------------------------
    # Newsletter
    # -------------------------------
    entity_manager.newsletter_subscription:
        class: Doctrine\Bundle\DoctrineBundle\Registry
        factory: ["@doctrine", getManagerForClass]
        arguments:
            - AppBundle\Entity\NewsletterSubscription

    service.newsletter:
        class: AppBundle\Service\NewsletterService
        arguments:
            - "@entity_manager.newsletter_subscription"

    # -------------------------------
    # Recipe
    # -------------------------------
    repository.recipe:
        class: AppBundle\Repository\RecipeRepository
        public: true

    # -------------------------------
    # Comment
    # -------------------------------
    repository.comment:
        class: AppBundle\Repository\CommentRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Comment

