# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    entity_manager.recipe:
        class: Doctrine\Bundle\DoctrineBundle\Registry
        factory: ["@doctrine", getManagerForClass]
        arguments:
            - AppBundle\Entity\Recipe

    repository.recipe:
        class: AppBundle\Repository\RecipeRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Recipe
